# .github/workflows/ci.yml
name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta] # Test on stable and beta toolchains

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain (${{ matrix.toolchain }})
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Run Clippy (linter)
      run: cargo clippy --all-targets -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose 